"""empty message

Revision ID: e19abcbac36f
Revises: 6cbfb2d18ddf
Create Date: 2026-03-30 17:14:57.230496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19abcbac36f'
down_revision = '6cbfb2d18ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint('empresa_nombre_key', ['nombre'])

    # ### end Alembic commands ###
